// Generated using Sourcery 0.16.2 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

// swiftlint:disable file_length

/** Found 99 Types
 * AESError
 * AppDelegate
 * BaseAddressError
 * Bool
 * CStructWrapper
 * CStructWrapper.CodingKeys
 * ClassMemoryBytesWrapper
 * ClassMemoryBytesWrapper.CodingKeys
 * CodableError
 * DBSecurityAide
 * Data
 * Date
 * Decodable
 * Double
 * Encodable
 * FastFileMD5HashParam
 * FileManagerAide
 * FileURL
 * FileURL.CodingKeys
 * FileURLTests
 * FileURLType
 * Float
 * Int
 * Int16
 * Int32
 * Int64
 * Int8
 * JSONDecoder
 * JSONEncoder
 * JSONStringAide
 * KVDBService
 * KVDBServiceAide
 * KVDBServiceTests
 * KVFileService
 * KVFileServiceAide
 * KVFileServiceTests
 * KVJSONAide
 * KVKeyChainService
 * KVKeyChainServiceTests
 * KeyChainService
 * MemoryBytesAide
 * MyClass
 * MyEnum
 * OCCodingObjectArrayWrapper
 * OCCodingObjectArrayWrapper.CodingKeys
 * OCCodingObjectWrapper
 * OCCodingObjectWrapper.CodingKeys
 * OCEnumWrapper
 * OCEnumWrapper.CodingKeys
 * ORMDBService
 * ORMDBServiceAide
 * ORMDBServiceInnerAide
 * ORMDBServiceTests
 * ORMTableInfoAide
 * ORMTableInfoModel
 * ORMTableInfoModel.CodingKeys
 * ParamConfigModel
 * PathAide
 * PersistentService
 * PersistentServiceAide
 * SQLCipherAide
 * SQLCipherError
 * SQLCipherTests
 * SQLiteRecordDecoder
 * SQLiteRecordDecoder.CICOSQLiteRecordKeyedDecodingContainer
 * SQLiteRecordDecoderError
 * SQLiteRecordEncoder
 * SQLiteRecordEncoder.CICOSQLiteRecordKeyedEncodingContainer
 * SQLiteType
 * SQLiteTypeDecoder
 * SQLiteTypeDecoder.CICOTypeKeyedDecodingContainer
 * SQLiteTypeDecoderError
 * SecurityAide
 * SecurityAide.AESType
 * SecurityAide.HMACType
 * SecurityAide.SHAType
 * SecurityAideTests
 * SizedPointer
 * String
 * StructMemoryBytesWrapper
 * StructMemoryBytesWrapper.CodingKeys
 * TClassBase
 * TClassChild
 * TCodableClass
 * TCodableClass.CodingKeys
 * TCodableStruct
 * TCodableStruct.CodingKeys
 * TStructOne
 * TStructTwo
 * TypeProperty
 * UInt
 * UInt16
 * UInt32
 * UInt64
 * UInt8
 * URL
 * URLKVFileService
 * URLKVFileServiceTests
 * ViewController
 */

/** Found 5 CICOAutoCodable Types
 * MyClass
 * MyEnum
 * ORMTableInfoModel
 * TCodableClass
 * TCodableStruct
 */
